import java.util.ArrayList;
import java.util.List;

public class Test {

	public static void main(String[] args) {
		List<PopMusic> list = new ArrayList<PopMusic>();
		list.add(new PopMusic("Single Ladies (Put a Ring on It)", "Beyonce", 2008,
				"All the single ladies, all the single ladies\r\n" + "All the single ladies, all the single ladies\r\n"
						+ "All the single ladies, all the single ladies\r\n" + "All the single ladies\r\n"
						+ "Now put your hands up\r\n" + "Up in the club, we just broke up\r\n"
						+ "I'm doing my own little thing\r\n" + "Decided to dip and now you wanna trip\r\n"
						+ "Cause another brother noticed me\r\n" + "I'm up on him, he up on me\r\n"
						+ "Don't pay him any attention\r\n" + "Just cried my tears, for three good years\r\n"
						+ "Ya can't be mad at me\r\n"
						+ "Cause if you liked it then you should have put a ring on it\r\n"
						+ "If you liked it then you shoulda put a ring on it\r\n"
						+ "Don't be mad once you see that he want it\r\n"
						+ "If you liked it then you shoulda put a ring on it\r\n"
						+ "Oh, oh, oh, oh, oh, oh, oh, o-ohh\r\n" + "Oh, oh, oh, oh, oh, oh, oh, o-ohh\r\n"
						+ "If you liked it then you should have put a ring on it\r\n"
						+ "If you liked it then you shoulda put a ring on it\r\n"
						+ "Don't be mad once you see that he want it\r\n"
						+ "If you liked it then you shoulda put a ring on it\r\n"
						+ "I got gloss on my lips, a man on my hips\r\n" + "Got me tighter in my Dereon jeans\r\n"
						+ "Acting up, drink in my cup\r\n" + "I can care less what you think\r\n"
						+ "I need no permission, did I mention\r\n" + "Don't pay him any attention\r\n"
						+ "Cause you had your turn and now you gonna learn\r\n"
						+ "What it really feels like to miss me\r\n"
						+ "Cause if you liked it then you should have put a ring on it\r\n"
						+ "If you liked it then you shoulda put a ring on it\r\n"
						+ "Don't be mad once you see that he want it\r\n"
						+ "If you liked it then you shoulda put a ring on it\r\n" + "Oh, oh, oh, oh, oh, oh, oh\r\n"
						+ "If you liked it then you should have put a ring on it\r\n"
						+ "If you liked it then you shoulda put a ring on it\r\n"
						+ "Don't be mad once you see that he want it\r\n"
						+ "If you liked it then you shoulda put a ring on it\r\n" + "Oh, oh, oh, oh, oh, oh, oh, oh\r\n"
						+ "Don't treat me to the things of the world\r\n" + "I'm not that kind of girl\r\n"
						+ "Your love is what I prefer, what I deserve\r\n"
						+ "Here's a man that makes me then takes me\r\n"
						+ "And delivers me to a destiny, to infinity and beyond\r\n"
						+ "Pull me into your arms, say I'm the one you own\r\n" + "If you don't, you'll be alone\r\n"
						+ "And like a ghost Ill be gone\r\n" + "All the single ladies, all the single ladies\r\n"
						+ "All the single ladies, all the single ladies\r\n"
						+ "All the single ladies, all the single ladies\r\n" + "All the single ladies\r\n"
						+ "Now put your hands up, oh, oh, oh, oh, oh, oh, oh\r\n"
						+ "Cause if you liked it then you should have put a ring on it\r\n"
						+ "If you liked it then you shoulda put a ring on it\r\n"
						+ "Don't be mad once you see that he want it\r\n"
						+ "If you liked it then you shoulda put a ring on it\r\n" + "Oh, oh, oh\r\n"
						+ "If you liked it then you should have put a ring on it\r\n"
						+ "If you liked it then you shoulda put a ring on it\r\n"
						+ "Don't be mad once you see that he want it\r\n"
						+ "If you liked it then you shoulda put a ring on it\r\n" + "Oh, oh, oh"));
		list.add(new PopMusic("Umbrella", "Rihanna", 2007, "Uh huh, uh huh\r\n" + "Yeah, Rihanna\r\n"
				+ "Uh huh, uh huh\r\n" + "Good girl gone bad\r\n" + "Uh huh, uh huh\r\n" + "Take three, action\r\n"
				+ "Uh huh, uh huh, Hov\r\n" + "No clouds in my stones\r\n" + "Let it rain, I hydroplane in the bank\r\n"
				+ "Comin' down at the Dow Jones\r\n" + "When the clouds come, we gone\r\n" + "We Rocafella\r\n"
				+ "We fly higher than weather\r\n" + "In G5s or better\r\n" + "You know me\r\n"
				+ "In anticipation for precipitation stack chips for the rainy day\r\n"
				+ "Rain Man is back with little Ms. Sunshine\r\n" + "Rihanna, where you at?\r\n"
				+ "You have my heart, and we'll never be worlds apart\r\n"
				+ "Maybe in magazines, but you'll still be my star\r\n" + "Baby, 'cause in the dark\r\n"
				+ "You can't see shiny cars\r\n" + "And that's when you need me there\r\n"
				+ "With you I'll always share\r\n" + "Because\r\n" + "When the sun shines, we'll shine together\r\n"
				+ "Told you I'll be here forever\r\n" + "Said I'll always be your friend\r\n"
				+ "Took an oath, I'ma stick it out 'til the end\r\n" + "Now that it's raining more than ever\r\n"
				+ "Know that we'll still have each other\r\n" + "You can stand under my umbrella\r\n"
				+ "You can stand under my umbrella, ella, ella, eh, eh, eh\r\n"
				+ "Under my umbrella, ella, ella, eh, eh, eh\r\n" + "Under my umbrella, ella, ella, eh, eh, eh\r\n"
				+ "Under my umbrella, ella, ella, eh, eh, eh, eh, eh, eh\r\n"
				+ "These fancy things will never come in between\r\n"
				+ "You're part of my entity, here for infinity\r\n" + "When the world has took its part\r\n"
				+ "When the world has dealt its cards\r\n" + "If the hand is hard, together we'll mend your heart\r\n"
				+ "Because\r\n" + "When the sun shines, we shine together\r\n" + "Told you I'll be here forever\r\n"
				+ "Said I'll always be your friend\r\n" + "Took an oath, I'ma stick it out 'til the end\r\n"
				+ "Now that it's raining more than ever\r\n" + "Know that we'll still have each other\r\n"
				+ "You can stand under my umbrella\r\n" + "You can stand under my umbrella, ella, ella, eh, eh, eh\r\n"
				+ "Under my umbrella, ella, ella, eh, eh, eh\r\n" + "Under my umbrella, ella, ella, eh, eh, eh\r\n"
				+ "Under my umbrella, ella, ella, eh, eh, eh, eh, eh, eh\r\n" + "You can run into my arms\r\n"
				+ "It's okay, don't be alarmed\r\n" + "Come into me\r\n"
				+ "(There's no distance in between our love)\r\n" + "So gon' and let the rain pour\r\n"
				+ "I'll be all you need and more\r\n" + "Because\r\n" + "When the sun shines, we shine together\r\n"
				+ "Told you I'll be here forever\r\n" + "Said I'll always be your friend\r\n"
				+ "Took an oath, I'ma stick it out 'til the end\r\n" + "Now that it's raining more than ever\r\n"
				+ "Know that we'll still have each other\r\n" + "You can stand under my umbrella\r\n"
				+ "You can stand under my umbrella, ella, ella, eh, eh, eh\r\n"
				+ "Under my umbrella, ella, ella, eh, eh, eh\r\n" + "Under my umbrella, ella, ella, eh, eh, eh\r\n"
				+ "Under my umbrella, ella, ella, eh, eh, eh, eh, eh, eh\r\n" + "It's raining, raining\r\n"
				+ "Ooh, baby, it's raining, raining\r\n" + "Baby, come into me\r\n" + "Come into me\r\n"
				+ "It's raining, raining\r\n" + "Ooh, baby, it's raining, raining\r\n"
				+ "You can always come into me\r\n" + "Come into me\r\n" + "It's pouring rain\r\n"
				+ "It's pouring rain\r\n" + "Come into me\r\n" + "Come into me\r\n" + "It's pouring rain\r\n"
				+ "It's pouring rain"));
		list.add(new PopMusic("Shake it Off", "Taylor Swift" + "", 2016,
				"I stay out too late, got nothing in my brain\r\n"
						+ "That's what people say, that's what people say\r\n"
						+ "I go on too many dates, but I can't make them stay\r\n"
						+ "At least that's what people say, that's what people say\r\n" + "But I keep cruising\r\n"
						+ "Can't stop, won't stop moving\r\n" + "It's like I got this music in my mind\r\n"
						+ "Saying it's gonna be alright\r\n" + "I never miss a beat, I'm lightning on my feet\r\n"
						+ "And that's what they don't see, that's what they don't see\r\n"
						+ "Players gonna play, play, play, play, play\r\n"
						+ "And the haters gonna hate, hate, hate, hate, hate (haters gonna hate)\r\n"
						+ "Baby, I'm just gonna shake, shake, shake, shake, shake\r\n"
						+ "I shake it off, I shake it off\r\n" + "Heartbreakers gonna break\r\n"
						+ "Fakers gonna fake\r\n" + "I'm just gonna shake\r\n" + "I shake it off, I shake it off\r\n"
						+ "I shake it off, I shake it off\r\n" + "I, I, I shake it off, I shake it off\r\n"
						+ "I, I, I shake it off, shake it off\r\n" + "I, I, I shake it off, I shake it off\r\n"
						+ "I, I, I shake it off, I shake it off\r\n" + "I, I, I shake it off, I shake it off\r\n"
						+ "I, I, I, shake it off, I shake it off\r\n" + "I, I, I, shake it off, I shake it off"));
		list.add(new PopMusic("Toxic", "Britney Spears" + "", 2004, "Baby, can't you see I'm calling?\r\n"
				+ "A guy like you should wear a warning\r\n" + "It's dangerous, I'm falling\r\n"
				+ "There's no escape, I can't wait\r\n" + "I need a hit, baby, give me it\r\n"
				+ "You're dangerous, I'm loving it\r\n" + "Too high, can't come down\r\n"
				+ "Losing my head, spinnin' 'round and 'round\r\n" + "Do you feel me now?\r\n"
				+ "With a taste of your lips, I'm on a ride\r\n" + "You're toxic, I'm slippin' under\r\n"
				+ "With a taste of a poison paradise\r\n" + "I'm addicted to you\r\n"
				+ "Don't you know that you're toxic?\r\n" + "And I love what you do\r\n"
				+ "Don't you know that you're toxic?\r\n" + "It's getting late to give you up\r\n"
				+ "I took a sip from my devil's cup\r\n" + "Slowly, it's taking over me\r\n"
				+ "Too high, can't come down\r\n" + "It's in the air and it's all around\r\n"
				+ "Can you feel me now?\r\n" + "With a taste of your lips, I'm on a ride\r\n"
				+ "You're toxic, I'm slippin' under\r\n" + "With a taste of a poison paradise\r\n"
				+ "I'm addicted to you\r\n" + "Don't you know that you're toxic?\r\n" + "And I love what you do\r\n"
				+ "Don't you know that you're toxic?\r\n" + "Don't you know that you're toxic?\r\n"
				+ "Taste of your lips, I'm on a ride\r\n" + "You're toxic, I'm slippin' under\r\n"
				+ "With a taste of a poison paradise\r\n" + "I'm addicted to you\r\n"
				+ "Don't you know that you're toxic?\r\n" + "With a taste of your lips, I'm on a ride\r\n"
				+ "You're toxic, I'm slippin' under (toxic)\r\n" + "With a taste of a poison paradise\r\n"
				+ "I'm addicted to you\r\n" + "Don't you know that you're toxic?\r\n"
				+ "Intoxicate me now, with your lovin' now\r\n" + "I think I'm ready now, I think I'm ready now\r\n"
				+ "Intoxicate me now, with your lovin' now\r\n" + "I think I'm ready now"));
		list.add(new PopMusic("Rolling in the Deep", "Adele", 2011, "There's a fire starting in my heart\r\n"
				+ "Reaching a fever pitch, it's bringing me out the dark\r\n"
				+ "Finally I can see you crystal clear\r\n" + "Go 'head and sell me out and I'll lay your ship bare\r\n"
				+ "See how I'll leave with every piece of you\r\n" + "Don't underestimate the things that I will do\r\n"
				+ "There's a fire starting in my heart\r\n"
				+ "Reaching a fever pitch and it's bringing me out the dark\r\n"
				+ "The scars of your love remind me of us\r\n" + "They keep me thinking that we almost had it all\r\n"
				+ "The scars of your love they leave me breathless\r\n" + "I can't help feeling\r\n"
				+ "We could've had it all (you're gonna wish you)\r\n" + "(Never had met me)\r\n"
				+ "Rolling in the deep (tears are gonna fall)\r\n" + "(Rolling in the deep)\r\n"
				+ "You had my heart inside (you're gonna wish you)\r\n" + "Of your hands (never had met me)\r\n"
				+ "And you played it (tears are gonna fall)\r\n" + "To the beat (rolling in the deep)\r\n"
				+ "Baby, I have no story to be told\r\n"
				+ "But I've heard one on you, now I'm gonna make your head burn\r\n"
				+ "Think of me in the depths of your despair\r\n"
				+ "Make a home down there, as mine sure won't be shared\r\n"
				+ "The scars of your love (never had met me)\r\n" + "Remind me of us (tears are gonna fall)\r\n"
				+ "They keep me thinking (rolling in the deep)\r\n"
				+ "That we almost had it all (you're gonna wish you)\r\n"
				+ "The scars of your love (never had met me)\r\n"
				+ "They leave me breathless (tears are gonna fall)\r\n"
				+ "I can't help feeling (rolling in the deep)\r\n"
				+ "We could've had it all (you're gonna wish you)\r\n" + "(Never had met me)\r\n"
				+ "Rolling in the deep (tears are gonna fall)\r\n" + "(Rolling in the deep)\r\n"
				+ "You had my heart inside (you're gonna wish you)\r\n" + "Of your hands (never had met me)\r\n"
				+ "And you played it (tears are gonna fall)\r\n" + "To the beat (rolling in the deep)\r\n"
				+ "We could've had it all\r\n" + "Rolling in the deep\r\n" + "You had my heart inside of your hand\r\n"
				+ "But you played it with a beating\r\n" + "Throw your soul through every open door (whoa)\r\n"
				+ "Count your blessings to find what you look for (whoa)\r\n"
				+ "Turn my sorrow into treasured gold (whoa)\r\n"
				+ "You pay me back in kind and reap just what you've sown\r\n"
				+ "We could've had it all (tears are gonna fall, rolling in the deep)\r\n"
				+ "We could've had it all (you're gonna wish you never had met me)\r\n"
				+ "It all, it all, it all (tears are gonna fall, rolling in the deep)\r\n"
				+ "We could've had it all (you're gonna wish you)\r\n" + "(Never had met me)\r\n"
				+ "Rolling in the deep (tears are gonna fall)\r\n" + "(Rolling in the deep)\r\n"
				+ "You had my heart inside (you're gonna wish you)\r\n" + "Of your hands (never had met me)\r\n"
				+ "And you played it (tears are gonna fall)\r\n" + "To the beat (rolling in the deep)\r\n"
				+ "Could've had it all (you're gonna wish you)\r\n" + "(Never had met me)\r\n"
				+ "Rolling in the deep (tears are gonna fall)\r\n" + "(Rolling in the deep)\r\n"
				+ "You had my heart inside (you're gonna wish you)\r\n" + "Of your hands (never had met me)\r\n"
				+ "But you played it, you played it, you played it\r\n" + "You played it to the beat"));
		list.add(new PopMusic("Firework", "Katy Perry" + "", 2010, "Do you ever feel like a plastic bag\r\n"
				+ "Drifting through the wind, wanting to start again?\r\n" + "Do you ever feel, feel so paper thin\r\n"
				+ "Like a house of cards, one blow from cavin' in?\r\n" + "Do you ever feel already buried deep?\r\n"
				+ "Six feet under screams, but no one seems to hear a thing\r\n"
				+ "Do you know that there's still a chance for you?\r\n" + "'Cause there's a spark in you\r\n"
				+ "You just gotta ignite the light\r\n" + "And let it shine\r\n" + "Just own the night\r\n"
				+ "Like the Fourth of July\r\n" + "'Cause baby, you're a firework\r\n"
				+ "Come on, show 'em what you're worth\r\n" + "Make 'em go, \"Oh, oh, oh\"\r\n"
				+ "As you shoot across the sky\r\n" + "Baby, you're a firework\r\n"
				+ "Come on, let your colors burst\r\n" + "Make 'em go, \"Oh, oh, oh\"\r\n"
				+ "You're gonna leave 'em all in awe, awe, awe\r\n" + "You don't have to feel like a waste of space\r\n"
				+ "You're original, cannot be replaced\r\n" + "If you only knew what the future holds\r\n"
				+ "After a hurricane comes a rainbow\r\n" + "Maybe a reason why all the doors are closed\r\n"
				+ "So you could open one that leads you to the perfect road\r\n"
				+ "Like a lightning bolt, your heart will glow\r\n" + "And when it's time, you'll know\r\n"
				+ "You just gotta ignite the light\r\n" + "And let it shine\r\n" + "Just own the night\r\n"
				+ "Like the Fourth of July\r\n" + "'Cause baby, you're a firework\r\n"
				+ "Come on, show 'em what you're worth\r\n" + "Make 'em go, \"Oh, oh, oh\"\r\n"
				+ "As you shoot across the sky\r\n" + "Baby, you're a firework\r\n"
				+ "Come on, let your colors burst\r\n" + "Make 'em go, \"Oh, oh, oh\"\r\n"
				+ "You're gonna leave 'em all in awe, awe, awe\r\n" + "Boom, boom, boom\r\n"
				+ "Even brighter than the moon, moon, moon\r\n" + "It's always been inside of you, you, you\r\n"
				+ "And now it's time to let it through\r\n" + "'Cause baby, you're a firework\r\n"
				+ "Come on, show 'em what you're worth\r\n" + "Make 'em go, \"Oh, oh, oh\"\r\n"
				+ "As you shoot across the sky\r\n" + "Baby, you're a firework\r\n"
				+ "Come on, let your colors burst\r\n" + "Make 'em go, \"Oh, oh, oh\"\r\n"
				+ "You're gonna leave 'em all in awe, awe, awe\r\n" + "Boom, boom, boom\r\n"
				+ "Even brighter than the moon, moon, moon\r\n" + "Boom, boom, boom\r\n"
				+ "Even brighter than the moon, moon, moon"));
		list.add(new PopMusic("Rehab", "Amy Winehouse", 2006, "They tried to make me go to Rehab\r\n"
				+ "But I said no, no, no\r\n" + "Yes I've been black, but when I come back\r\n"
				+ "You'll know, know, know\r\n" + "I ain't got the time\r\n" + "And if my daddy thinks I'm fine\r\n"
				+ "They tried to make me go to Rehab\r\n" + "But I won't go, go, go\r\n"
				+ "I'd rather be at home with Ray\r\n" + "I ain't got seventy days\r\n" + "'Cause there's nothing\r\n"
				+ "There's nothing you can teach me\r\n" + "That I can't learn from Mr. Hathaway\r\n"
				+ "I didn't get a lot in class\r\n" + "But I know it don't come in a shot glass\r\n"
				+ "They tried to make me go to Rehab\r\n" + "But I said no, no, no\r\n"
				+ "Yes I've been black, but when I come back\r\n" + "You'll know, know, know\r\n"
				+ "I ain't got the time\r\n" + "And if my daddy thinks I'm fine\r\n"
				+ "They tried to make me go to Rehab\r\n" + "But I won't go, go, go\r\n"
				+ "The man said, \"Why you think you here?\"\r\n" + "I said, \"I got no idea\"\r\n"
				+ "\"I'm gonna, I'm gonna lose my baby\"\r\n" + "\"So I always keep a bottle near\"\r\n"
				+ "He said, \"I just think you're depressed\"\r\n" + "\"This me, yeah baby, and the rest\"\r\n"
				+ "They tried to make me go to Rehab\r\n" + "But I said no, no, no\r\n"
				+ "Yes I've been black, but when I come back\r\n" + "You'll know, know, know\r\n"
				+ "I don't ever want to drink again\r\n" + "I just, ooh, I just need a friend\r\n"
				+ "I'm not gonna spend ten weeks\r\n" + "And have everyone think I'm on the mend\r\n"
				+ "And it's not just my pride\r\n" + "It's just 'til these tears have dried\r\n"
				+ "They tried to make me go to Rehab\r\n" + "But I said no, no, no\r\n"
				+ "Yes I've been black, but when I come back\r\n" + "You'll know, know, know\r\n"
				+ "I ain't got the time\r\n" + "And if my daddy thinks I'm fine\r\n"
				+ "They try to make me go to Rehab\r\n" + "But I won't go, go, go!"));
		list.add(new PopMusic("Blinding Lights", "The Weeknd", 2019, "Yeah\r\n" + "I've been tryna call\r\n"
				+ "I've been on my own for long enough\r\n" + "Maybe you can show me how to love, maybe\r\n"
				+ "I'm going through withdrawals\r\n" + "You don't even have to do too much\r\n"
				+ "You can turn me on with just a touch, baby\r\n" + "I look around and\r\n"
				+ "Sin City's cold and empty (oh)\r\n" + "No one's around to judge me (oh)\r\n"
				+ "I can't see clearly when you're gone\r\n" + "I said, ooh, I'm blinded by the lights\r\n"
				+ "No, I can't sleep until I feel your touch\r\n" + "I said, ooh, I'm drowning in the night\r\n"
				+ "Oh, when I'm like this, you're the one I trust\r\n" + "(Hey, hey, hey)\r\n"
				+ "I'm running out of time\r\n" + "'Cause I can see the sun light up the sky\r\n"
				+ "So I hit the road in overdrive, baby, oh\r\n" + "The city's cold and empty (oh)\r\n"
				+ "No one's around to judge me (oh)\r\n" + "I can't see clearly when you're gone\r\n"
				+ "I said, ooh, I'm blinded by the lights\r\n" + "No, I can't sleep until I feel your touch\r\n"
				+ "I said, ooh, I'm drowning in the night\r\n" + "Oh, when I'm like this, you're the one I trust\r\n"
				+ "I'm just walking by to let you know (by to let you know)\r\n"
				+ "I can never say it on the phone (say it on the phone)\r\n"
				+ "Will never let you go this time (ooh)\r\n" + "I said, ooh, I'm blinded by the lights\r\n"
				+ "No, I can't sleep until I feel your touch\r\n" + "(Hey, hey, hey)\r\n"
				+ "I said, ooh, I'm blinded by the lights\r\n" + "No, I can't sleep until I feel your touch"));
		list.add(new PopMusic("Dancing on My Own", "Robyn", 2016, "Somebody said you got a new friend\r\n"
				+ "Does she love you better than I can?\r\n" + "And there's a big black sky over my town\r\n"
				+ "I know where you're at, I bet she's around\r\n" + "And yeah, I know it's stupid\r\n"
				+ "But I just gotta see it for myself\r\n" + "I'm in the corner, watching you kiss her, oh\r\n"
				+ "I'm right over here, why can't you see me? Oh\r\n" + "And I'm giving it my all\r\n"
				+ "I'm not the guy you're taking home, ooh\r\n" + "I keep dancing on my own, ah\r\n"
				+ "I just wanna dance all night\r\n" + "And I'm all messed up, I'm so out of line, yeah\r\n"
				+ "Stilettos and broken bottles\r\n" + "I'm spinning around in circles\r\n"
				+ "And I'm in the corner, watching you kiss her, oh\r\n"
				+ "And I'm right over here, why can't you see me? Oh\r\n" + "And I'm giving it my all\r\n"
				+ "But I'm not the guy you're taking home, ooh\r\n" + "I keep dancing on my own\r\n" + "And oh, nah\r\n"
				+ "So far away but still so near\r\n" + "The lights come on, the music dies\r\n"
				+ "But you don't see me standing here\r\n" + "I just came to say goodbye\r\n"
				+ "I'm in the corner, watching you kiss her, oh\r\n" + "And I'm giving it my all\r\n"
				+ "But I'm not the guy you're taking home, ooh\r\n" + "I keep dancing on my own\r\n" + "And oh, nah\r\n"
				+ "Said, I'm in the corner, watching you kiss her, oh no\r\n"
				+ "And I'm right over here, why can't you see me? Oh no\r\n" + "And I'm giving it my all\r\n"
				+ "But I'm not the guy you're taking home, ooh\r\n" + "I keep dancing on my own\r\n"
				+ "So far away, but still so near\r\n" + "The lights come on, the music dies\r\n"
				+ "But you don't see me standing here"));
		list.add(new PopMusic("Hey Ya!", "Outkast", 2003, "One, two, three, uh\r\n" + "My baby don't mess around\r\n"
				+ "Because she loves me so\r\n" + "And this I know fo sho (uh)\r\n" + "But does she really wanna\r\n"
				+ "But can't stand to see me walk out the door? (Ah)\r\n" + "Don't try to fight the feeling\r\n"
				+ "Because the thought alone is killin' me right now (uh)\r\n" + "Thank God for Mom and Dad\r\n"
				+ "For sticking two together\r\n" + "'Cause we don't know how (c'mon)\r\n" + "Hey ya! Hey ya!\r\n"
				+ "Hey ya! Hey ya!\r\n" + "Hey ya! Hey ya!\r\n" + "Hey ya! Hey ya!\r\n" + "You think you've got it\r\n"
				+ "Oh, you think you've got it\r\n" + "But got it just don't get it 'til there's nothin' at all\r\n"
				+ "We get together\r\n" + "Oh, we get together\r\n"
				+ "But separate's always better when there's feelings involved\r\n" + "If what they say is\r\n"
				+ "\"Nothing is forever\"\r\n" + "Then what makes, then what makes\r\n"
				+ "Then what makes, then what makes (what makes, what makes)\r\n" + "Love the exception?\r\n"
				+ "So why, oh, why, oh\r\n" + "Why, oh, why, oh, why, oh\r\n"
				+ "Are we so in denial when we know we're not happy here?\r\n"
				+ "(Y'all don't want to hear me, you just want to dance)\r\n" + "Hey ya! (Uh oh) Hey ya! (Uh oh)\r\n"
				+ "Don't want to meet your daddy\r\n" + "Hey ya! (Uh oh)\r\n" + "Just want you in my Caddy (Uh oh)\r\n"
				+ "Hey ya! (Uh oh)\r\n" + "Don't want to meet your mama\r\n" + "Hey ya! (Uh oh)\r\n"
				+ "Just want to make you cum-a (Uh oh)\r\n" + "Hey ya! (Uh oh)\r\n"
				+ "I'm, I'm, I'm just being honest (Uh oh)\r\n" + "I'm just being honest\r\n" + "Hey! Alright now\r\n"
				+ "Alright now, fellas (Yeah?)\r\n" + "Now, what cooler than being cool? (Ice cold!)\r\n"
				+ "I can't hear you\r\n" + "I say what's, what's cooler than being cool? (Ice cold!)\r\n"
				+ "Alright, alright, alright, alright, alright\r\n" + "Alright, alright, alright, alright, alright\r\n"
				+ "Alright, alright, alright, alright\r\n" + "Okay, now ladies (Yeah?)\r\n"
				+ "Now, we gon' break this thang down in just a few seconds\r\n"
				+ "Now, don't have me break this thang down for nothin'\r\n"
				+ "Now, I want to see y'all on y'all baddest behavior\r\n"
				+ "Lend me some sugar, I am your neighbor\r\n" + "Ah! Here we go\r\n"
				+ "Shake it, shake, shake it, shake it, shake, shake it (Uh oh)\r\n"
				+ "Shake it, shake, shake it, shake it, shake it (Uh oh)\r\n"
				+ "Shake it like a Polaroid picture, hey ya!\r\n"
				+ "Shake it, shake, shake it, shake it, shake, shake it\r\n" + "Shake it, shake it, shake it, sugar\r\n"
				+ "Shake it like a Polaroid picture\r\n" + "Now, all Beyonce's, and Lucy Liu's\r\n"
				+ "And baby dolls\r\n" + "Get on the floor\r\n" + "Get on the floor, you know what to do\r\n"
				+ "You know what to do\r\n" + "You know what to do\r\n" + "Hey ya! (Uh oh) Hey ya! (Uh oh)\r\n"
				+ "Hey ya! (Uh oh) Hey ya! (Uh oh)\r\n" + "Hey ya! (Uh oh) Hey ya! (Uh oh)\r\n"
				+ "Hey ya! (Uh oh) Hey ya! (Uh oh)"));
		list.add(new PopMusic("Hips Don't Lie", "Shakira featuring Wyclef Jean" + "", 2005,
				"Ladies up in here tonight\r\n" + "No fighting\r\n" + "We got the refugees up in here (no fighting)\r\n"
						+ "No fighting\r\n" + "Shakira, Shakira\r\n"
						+ "I never really knew that she could dance like this (hey)\r\n"
						+ "She make a man wants to speak Spanish\r\n" + "¿Cómo se llama? (Sí), bonita (sí)\r\n"
						+ "Mi casa, su casa (Shakira, Shakira)\r\n" + "Oh, baby, when you talk like that\r\n"
						+ "You make a woman go mad\r\n" + "So be wise (sí) and keep on (sí)\r\n"
						+ "Reading the signs of my body (uno, dos, tres, cuatro)\r\n" + "I'm on tonight\r\n"
						+ "You know my hips don't lie (no fighting)\r\n" + "And I'm starting to feel it's right\r\n"
						+ "All the attraction, the tension\r\n" + "Don't you see, baby, this is perfection?\r\n"
						+ "Hey, girl, I can see your body moving\r\n" + "And it's driving me crazy\r\n"
						+ "And I didn't have the slightest idea\r\n" + "Until I saw you dancing (yeah)\r\n"
						+ "And when you walk up on the dance floor\r\n"
						+ "Nobody cannot ignore the way you move your body, girl (just move)\r\n"
						+ "And everything so unexpected, the way you right and left it\r\n"
						+ "So you can keep on shaking it (let's go)\r\n"
						+ "I never really knew that she could dance like this\r\n"
						+ "She make a man wants to speak Spanish\r\n" + "¿Cómo se llama? (Sí), bonita (sí)\r\n"
						+ "Mi casa, su casa (Shakira, Shakira)\r\n" + "Oh, baby, when you talk like that\r\n"
						+ "You make a woman go mad\r\n" + "So be wise (sí) and keep on (sí)\r\n"
						+ "Reading the signs of my body (no fighting)\r\n" + "I'm on tonight\r\n"
						+ "You know my hips don't lie (no fighting)\r\n" + "And I am starting to feel you, boy\r\n"
						+ "Come on, let's go, real slow\r\n" + "Don't you see, baby, así es perfecto?\r\n"
						+ "They know I am on tonight, my hips don't lie\r\n" + "And I'm starting to feel it's right\r\n"
						+ "All the attraction, the tension\r\n"
						+ "Don't you see, baby, this is perfection? (Shakira, Shakira)\r\n"
						+ "Oh, boy, I can see your body moving\r\n" + "Half animal, half man\r\n"
						+ "I don't, don't really know what I'm doing\r\n" + "But you seem to have a plan\r\n"
						+ "My will and self-restraint\r\n" + "Have come to fail now, fail now\r\n"
						+ "See, I am doing what I can, but I can't so you know\r\n"
						+ "That's a bit too hard to explain (uno, dos, tres, cuatro)\r\n"
						+ "Baila en la calle de noche (yeah)\r\n" + "Baila en la calle de día (let's go)\r\n"
						+ "Baila en la calle de noche\r\n" + "Baila en la calle de día\r\n"
						+ "I never really knew that she could dance like this\r\n"
						+ "She make a man wants to speak Spanish\r\n" + "¿Cómo se llama? (Sí), bonita (sí)\r\n"
						+ "Mi casa, su casa (Shakira, Shakira)\r\n" + "Oh, baby, when you talk like that\r\n"
						+ "You know you got me hypnotized\r\n" + "So be wise (sí) and keep on (sí)\r\n"
						+ "Reading the signs of my body\r\n" + "Señorita, feel the conga\r\n"
						+ "Let me see you move like you come from Colombia\r\n" + "Yeah (ladies sí) (yeah yeah)\r\n"
						+ "(Hey, yeah)\r\n" + "¡Mira en Barranquilla se baila así, say it! (yeah)\r\n"
						+ "En Barranquilla se baila así (yeah)\r\n" + "Hey, brra!\r\n"
						+ "Yeah, she's so sexy, every man's fantasy\r\n"
						+ "A refugee like me back with the Fugees from a third world country\r\n"
						+ "I go back like when 'Pac carried crates for Humpty Humpty\r\n"
						+ "We leave the whole club dizzy\r\n" + "Why the CIA wanna watch us?\r\n"
						+ "Colombians and Haitians\r\n" + "I ain't guilty, it's a musical transaction\r\n"
						+ "Bo bop so bop, no more do we snatch ropes\r\n"
						+ "Refugees run the seas 'cause we own our own boats (no fighting)\r\n"
						+ "I'm on tonight, my hips don't lie\r\n" + "And I'm starting to feel you, boy\r\n"
						+ "Come on, let's go, real slow\r\n" + "Baby, like this is perfecto (no fighting)\r\n"
						+ "Oh, you know I'm on tonight, my hips don't lie\r\n"
						+ "And I am starting to feel it's right\r\n" + "The attraction, the tension\r\n"
						+ "Baby, like this is perfection\r\n" + "No fighting\r\n" + "No fighting"));
		list.add(new PopMusic("SexyBack", "Justin Timberlake", 2006, "I'm bringing sexy back (yeah)\r\n"
				+ "Them other boys don't know how to act (yeah)\r\n"
				+ "I think you're special, what's behind your back? (Yeah)\r\n"
				+ "So turn around and I'll pick up the slack (yeah)\r\n" + "Take 'em to the bridge\r\n"
				+ "Dirty babe (uh-huh)\r\n" + "You see these shackles, baby, I'm your slave (uh-huh)\r\n"
				+ "I'll let you whip me if I misbehave (uh-huh)\r\n"
				+ "It's just that no one makes me feel this way (uh-huh)\r\n" + "Take 'em to the chorus\r\n"
				+ "Come here, girl (go 'head, be gone with it)\r\n" + "Come to the back (go 'head, be gone with it)\r\n"
				+ "V.I.P. (go 'head, be gone with it)\r\n" + "Drinks on me (go 'head, be gone with it)\r\n"
				+ "Let me see what you're twerking with (go 'head, be gone with it)\r\n"
				+ "Look at those hips (go 'head, be gone with it)\r\n"
				+ "You make me smile (go 'head, be gone with it)\r\n"
				+ "Go 'head child (go 'head, be gone with it), and\r\n"
				+ "Get your sexy on (go 'head, be gone with it)\r\n"
				+ "Get your sexy on (go 'head, be gone with it)\r\n"
				+ "Get your sexy on (go 'head, be gone with it)\r\n"
				+ "Get your sexy on (go 'head, be gone with it)\r\n"
				+ "Get your sexy on (go 'head, be gone with it)\r\n"
				+ "Get your sexy on (go 'head, be gone with it)\r\n"
				+ "Get your sexy on (go 'head, be gone with it)\r\n" + "Get your sexy on\r\n"
				+ "I'm bringing sexy back (yeah)\r\n" + "Them other fuckers don't know how to act (yeah)\r\n"
				+ "Girl, let me make up for the things you lack (yeah)\r\n"
				+ "'Cause you're burning up, I gotta get it fast (yeah)\r\n" + "Take 'em to the bridge\r\n"
				+ "Dirty babe (uh-huh)\r\n" + "You see these shackles, baby, I'm your slave (uh-huh)\r\n"
				+ "I'll let you whip me if I misbehave (uh-huh)\r\n"
				+ "It's just that no one makes me feel this way (uh-huh)\r\n" + "Take 'em to the chorus\r\n"
				+ "Come here, girl (go 'head, be gone with it)\r\n" + "Come to the back (go 'head, be gone with it)\r\n"
				+ "V.I.P. (go 'head, be gone with it)\r\n" + "Drinks on me (go 'head, be gone with it)\r\n"
				+ "Let me see what you're twerking with (go 'head, be gone with it)\r\n"
				+ "Look at those hips (go 'head, be gone with it)\r\n"
				+ "You make me smile (go 'head, be gone with it)\r\n"
				+ "Go 'head child (go 'head, be gone with it), and\r\n"
				+ "Get your sexy on (go 'head, be gone with it)\r\n"
				+ "Get your sexy on (go 'head, be gone with it)\r\n"
				+ "Get your sexy on (go 'head, be gone with it)\r\n"
				+ "Get your sexy on (go 'head, be gone with it)\r\n"
				+ "Get your sexy on (go 'head, be gone with it)\r\n"
				+ "Get your sexy on (go 'head, be gone with it)\r\n"
				+ "Get your sexy on (go 'head, be gone with it)\r\n" + "Get your sexy on\r\n" + "You ready?\r\n"
				+ "You ready?\r\n" + "You ready?\r\n" + "Uh (yes)\r\n" + "I'm bringing sexy back (yeah)\r\n"
				+ "You motherfuckers watch how I attack (yeah)\r\n"
				+ "If that's your girl you better watch your back (yeah)\r\n"
				+ "'Cause she'll burn it up for me and that's a fact (yeah)\r\n" + "Take 'em to the chorus, ha\r\n"
				+ "Come here, girl (go 'head, be gone with it)\r\n" + "Come to the back (go 'head, be gone with it)\r\n"
				+ "V.I.P. (go 'head, be gone with it)\r\n" + "Drinks on me (go 'head, be gone with it)\r\n"
				+ "Let me see what you're twerking with (go 'head, be gone with it)\r\n"
				+ "Look at those hips (go 'head, be gone with it)\r\n"
				+ "You make me smile (go 'head, be gone with it)\r\n"
				+ "Go 'head child (go 'head, be gone with it), and\r\n"
				+ "Get your sexy on (go 'head, be gone with it)\r\n"
				+ "Get your sexy on (go 'head, be gone with it)\r\n"
				+ "Get your sexy on (go 'head, be gone with it)\r\n"
				+ "Get your sexy on (go 'head, be gone with it)\r\n"
				+ "Get your sexy on (go 'head, be gone with it)\r\n"
				+ "Get your sexy on (go 'head, be gone with it)\r\n"
				+ "Get your sexy on (go 'head, be gone with it)\r\n" + "Get your sexy on\r\n" + "You ready? (Yes)\r\n"
				+ "You ready? (Yes)\r\n" + "(Yes)"));
		list.add(new PopMusic("Call Me Maybe", "Carly Rae Jepsen", 2012, "I threw a wish in the well\r\n"
				+ "Don't ask me, I'll never tell\r\n" + "I looked to you as it fell\r\n"
				+ "And now you're in my way\r\n" + "I trade my soul for a wish\r\n" + "Pennies and dimes for a kiss\r\n"
				+ "I wasn't looking for this\r\n" + "But now you're in my way\r\n" + "Your stare was holdin'\r\n"
				+ "Ripped jeans, skin was showin'\r\n" + "Hot night, wind was blowin'\r\n"
				+ "Where you think you're going, baby?\r\n" + "Hey, I just met you, and this is crazy\r\n"
				+ "But here's my number, so call me, maybe\r\n" + "It's hard to look right at you, baby\r\n"
				+ "But here's my number, so call me, maybe\r\n" + "Hey, I just met you, and this is crazy\r\n"
				+ "But here's my number, so call me, maybe\r\n" + "And all the other boys try to chase me\r\n"
				+ "But here's my number, so call me, maybe\r\n" + "You took your time with the call\r\n"
				+ "I took no time with the fall\r\n" + "You gave me nothing at all\r\n"
				+ "But still, you're in my way\r\n" + "I beg and borrow and steal\r\n"
				+ "At first sight, and it's real\r\n" + "I didn't know I would feel it\r\n" + "But it's in my way\r\n"
				+ "Your stare was holdin'\r\n" + "Ripped jeans, skin was showin'\r\n"
				+ "Hot night, wind was blowin'\r\n" + "Where you think you're going, baby?\r\n"
				+ "Hey, I just met you, and this is crazy\r\n" + "But here's my number, so call me, maybe\r\n"
				+ "It's hard to look right at you, baby\r\n" + "But here's my number, so call me, maybe\r\n"
				+ "Hey, I just met you, and this is crazy\r\n" + "But here's my number, so call me, maybe\r\n"
				+ "And all the other boys try to chase me\r\n" + "But here's my number, so call me, maybe\r\n"
				+ "Before you came into my life, I missed you so bad\r\n"
				+ "I missed you so bad, I missed you so, so bad\r\n"
				+ "Before you came into my life, I missed you so bad\r\n" + "And you should know that\r\n"
				+ "I missed you so, so bad\r\n" + "(Bad, bad, bad, bad, bad, bad)\r\n"
				+ "It's hard to look right at you, baby\r\n" + "But here's my number, so call me, maybe\r\n"
				+ "Hey, I just met you, and this is crazy\r\n" + "But here's my number, so call me, maybe\r\n"
				+ "And all the other boys try to chase me\r\n" + "But here's my number, so call me, maybe\r\n"
				+ "Before you came into my life, I missed you so bad\r\n"
				+ "I missed you so bad, I missed you so, so bad\r\n"
				+ "Before you came into my life, I missed you so bad\r\n" + "And you should know that\r\n"
				+ "So call me maybe"));
		list.add(new PopMusic("Uptown Funk", "Mark Ronson and Bruno Mars", 2014, "This hit, that ice cold\r\n"
				+ "Michelle Pfeiffer, that white gold\r\n" + "This one for them hood girls\r\n"
				+ "Them good girls straight masterpieces\r\n" + "Stylin', wilin', livin' it up in the city\r\n"
				+ "Got Chucks on with Saint Laurent\r\n" + "Gotta kiss myself, I'm so pretty\r\n"
				+ "I'm too hot (hot damn)\r\n" + "Call the police and the fireman\r\n" + "I'm too hot (hot damn)\r\n"
				+ "Make a dragon wanna retire man\r\n" + "I'm too hot (hot damn)\r\n"
				+ "Say my name you know who I am\r\n" + "I'm too hot (hot damn)\r\n"
				+ "And my band 'bout that money, break it down\r\n" + "Girls hit your hallelujah (whoo)\r\n"
				+ "Girls hit your hallelujah (whoo)\r\n" + "Girls hit your hallelujah (whoo)\r\n"
				+ "'Cause uptown funk gon' give it to you\r\n" + "'Cause uptown funk gon' give it to you\r\n"
				+ "'Cause uptown funk gon' give it to you\r\n" + "Saturday night and we in the spot\r\n"
				+ "Don't believe me just watch (come on)\r\n" + "Don't believe me just watch uh\r\n"
				+ "Don't believe me just watch\r\n" + "Don't believe me just watch\r\n"
				+ "Don't believe me just watch\r\n" + "Don't believe me just watch\r\n" + "Hey, hey, hey, oh\r\n"
				+ "Stop, wait a minute\r\n" + "Fill my cup, put some liquor in it\r\n" + "Take a sip, sign a check\r\n"
				+ "Julio, get the stretch\r\n" + "Ride to Harlem, Hollywood\r\n" + "Jackson, Mississippi\r\n"
				+ "If we show up, we gon' show out\r\n" + "Smoother than a fresh jar of Skippy\r\n"
				+ "I'm too hot (hot damn)\r\n" + "Call the police and the fireman\r\n" + "I'm too hot (hot damn)\r\n"
				+ "Make a dragon wanna retire man\r\n" + "I'm too hot (hot damn)\r\n"
				+ "Bitch say my name you know who I am\r\n" + "I'm too hot (hot damn)\r\n"
				+ "And my band 'bout that money\r\n" + "Break it down\r\n" + "Girls hit your hallelujah (whoo)\r\n"
				+ "Girls hit your hallelujah (whoo)\r\n" + "Girls hit your hallelujah (whoo)\r\n"
				+ "'Cause uptown funk gon' give it to you\r\n" + "'Cause uptown funk gon' give it to you\r\n"
				+ "'Cause uptown funk gon' give it to you\r\n" + "Saturday night and we in the spot\r\n"
				+ "Don't believe me just watch (come on)\r\n" + "Don't believe me just watch uh\r\n"
				+ "Don't believe me just watch uh\r\n" + "Don't believe me just watch uh\r\n"
				+ "Don't believe me just watch\r\n" + "Don't believe me just watch\r\n" + "Hey, hey, hey, oh\r\n"
				+ "Before we leave\r\n" + "Lemme tell y'all a lil' something\r\n" + "Uptown funk you up\r\n"
				+ "Uptown funk you up\r\n" + "Uptown funk you up\r\n" + "Uptown funk you up uh\r\n"
				+ "I said uptown funk you up\r\n" + "Uptown funk you up\r\n" + "Uptown funk you up\r\n"
				+ "Uptown funk you up\r\n" + "Come on, dance, jump on it\r\n" + "If you sexy then flaunt it\r\n"
				+ "If you freaky then own it\r\n" + "Don't brag about it, come show me\r\n" + "Come on, dance\r\n"
				+ "Jump on it\r\n" + "If you sexy then flaunt it\r\n"
				+ "Well it's Saturday night and we in the spot\r\n" + "Don't believe me just watch come on!\r\n"
				+ "Don't believe me just watch uh\r\n" + "Don't believe me just watch uh\r\n"
				+ "Don't believe me just watch uh\r\n" + "Don't believe me just watch\r\n"
				+ "Don't believe me just watch\r\n" + "Hey, hey, hey, oh\r\n" + "Uptown (woo) funk you up (come on)\r\n"
				+ "Uptown funk you up (say what?)\r\n" + "Uptown funk you up\r\n" + "Uptown funk you up (come on)\r\n"
				+ "Uptown (woo) funk you up (come on)\r\n" + "Uptown funk you up (say what?)\r\n"
				+ "Uptown funk you up\r\n" + "Uptown funk you up (come on)\r\n"
				+ "Uptown (woo) funk you up (come on)\r\n" + "Uptown funk you up (say what?)\r\n"
				+ "Uptown funk you up\r\n" + "Uptown funk you up (come on)\r\n" + "Uptown funk you up\r\n"
				+ "Uptown funk you up (say what?)\r\n" + "Uptown funk you up"));
		list.add(new PopMusic("Poker Face", "Lady Gaga", 2008,
				"I wanna hold 'em like they do in Texas, please (Woo)\r\n"
						+ "Fold 'em, let 'em hit me, raise it, baby, stay with me (I love it)\r\n"
						+ "LoveGame intuition, play the cards with spades to start\r\n"
						+ "And after he's been hooked, I'll play the one that's on his heart\r\n" + "\r\n"
						+ "Oh, whoa-oh, oh, oh\r\n" + "Oh-oh-oh-oh-oh-oh\r\n"
						+ "I'll get him hot, show him what I've got\r\n" + "Oh, whoa-oh, oh, oh\r\n"
						+ "Oh-oh-oh-oh-oh-oh\r\n" + "I'll get him hot, show him what I've got\r\n" + "\r\n"
						+ "Can't read my, can't read my\r\n" + "No, he can't read my poker face\r\n"
						+ "(She's got me like nobody)\r\n" + "Can't read my, can't read my\r\n"
						+ "No, he can't read my poker face\r\n" + "(She's got me like nobody)\r\n" + "\r\n"
						+ "P-p-p-poker face, f-f-fuck her face\r\n" + "(Mum mum mum mah)\r\n"
						+ "P-p-p-poker face, f-f-fuck her face\r\n" + "(Mum mum mum mah)\r\n" + "\r\n"
						+ "I wanna roll with him, a hard pair we will be (Woo)\r\n"
						+ "A little gamblin' is fun when you're with me (I love it, woo)\r\n"
						+ "Russian roulette is not the same without a gun\r\n"
						+ "And baby, when it's love, if it's not rough, it isn't fun, fun\r\n" + "\r\n"
						+ "Oh, whoa-oh, oh, oh\r\n" + "Oh-oh-oh-oh-oh-oh\r\n"
						+ "I'll get him hot, show him what I've got\r\n" + "Oh, whoa-oh, oh, oh\r\n"
						+ "Oh-oh-oh-oh-oh-oh\r\n" + "I'll get him hot, show him what I've got\r\n" + "\r\n"
						+ "Can't read my, can't read my\r\n" + "No, he can't read my poker face\r\n"
						+ "(She's got me like nobody)\r\n" + "Can't read my, can't read my\r\n"
						+ "No, he can't read my poker face\r\n" + "(She's got me like nobody)\r\n" + "\r\n"
						+ "P-p-p-poker face, f-f-fuck her face\r\n" + "(Mum mum mum mah)\r\n"
						+ "P-p-p-poker face, f-f-fuck her face\r\n" + "(Mum mum mum mah)\r\n" + "(Mum mum mum mah)\r\n"
						+ "(Mum mum mum mah)\r\n" + "\r\n" + "I won't tell you that I love you\r\n"
						+ "Kiss or hug you\r\n" + "'Cause I'm bluffin' with my muffin\r\n"
						+ "I'm not lyin', I'm just stunnin' with my love-glue-gunnin'\r\n"
						+ "Just like a chick in the casino\r\n" + "Take your bank before I pay you out\r\n"
						+ "I promise this, promise this\r\n" + "Check this hand 'cause I'm marvelous\r\n" + "\r\n"
						+ "Can't read my, can't read my\r\n" + "No, he can't read my poker face\r\n"
						+ "(She's got me like nobody)\r\n" + "Can't read my, can't read my\r\n"
						+ "No, he can't read my poker face\r\n" + "(She's got me like nobody)\r\n"
						+ "Can't read my, can't read my\r\n" + "No, he can't read my poker face\r\n"
						+ "(She's got me like nobody)\r\n" + "Can't read my, can't read my\r\n"
						+ "No, he can't read my poker face\r\n" + "(She's got me like nobody)\r\n"
						+ "Can't read my, can't read my\r\n" + "No, he can't read my poker face\r\n"
						+ "(She's got me like nobody)\r\n" + "Can't read my, can't read my\r\n"
						+ "No, he can't read my poker face\r\n" + "(She's got me like nobody)\r\n" + "\r\n"
						+ "P-p-p-poker face, f-f-fuck her face\r\n" + "P-p-p-poker face, f-f-fuck her face\r\n"
						+ "(She's got me like nobody)\r\n" + "P-p-p-poker face, f-f-fuck her face\r\n"
						+ "(Mum mum mum mah)\r\n" + "P-p-p-poker face, f-f-fuck her face\r\n" + "(Mum mum mum mah)\r\n"
						+ "P-p-p-poker face, f-f-fuck her face\r\n" + "(Mum mum mum mah)\r\n"
						+ "P-p-p-poker face, f-f-fuck her face\r\n" + "(Mum mum mum mah)"));
		list.add(new PopMusic("Hollaback Girl", "Gwen Stefani", 2004, "Uh huh, this my shit\r\n"
				+ "All the girls stomp your feet like this\r\n" + "A few times I've been around that track\r\n"
				+ "So it's not just gonna happen like that\r\n" + "'Cause I ain't no hollaback girl\r\n"
				+ "I ain't no hollaback girl\r\n" + "A few times I've been around that track\r\n"
				+ "So it's not just gonna happen like that\r\n" + "'Cause I ain't no hollaback girl\r\n"
				+ "I ain't no hollaback girl\r\n" + "Ooh, ooh, this my shit, this my shit\r\n"
				+ "Ooh, ooh, this my shit, this my shit\r\n" + "Ooh, ooh, this my shit, this my shit\r\n"
				+ "Ooh, ooh, this my shit, this my shit\r\n" + "I heard that you were talking shit\r\n"
				+ "And you didn't think that I would hear it\r\n" + "People hear you talking like that\r\n"
				+ "Getting everybody fired up\r\n" + "So I'm ready to attack, gonna lead the pack\r\n"
				+ "Gonna get a touchdown, gonna take you out\r\n" + "That's right, put your pom-poms downs\r\n"
				+ "Getting everybody fired up\r\n" + "A few times I've been around that track\r\n"
				+ "So it's not just gonna happen like that\r\n" + "'Cause I ain't no hollaback girl\r\n"
				+ "I ain't no hollaback girl\r\n" + "A few times I've been around that track\r\n"
				+ "So it's not just gonna happen like that\r\n" + "'Cause I ain't no hollaback girl\r\n"
				+ "I ain't no hollaback girl\r\n" + "Ooh, ooh, this my shit, this my shit\r\n"
				+ "Ooh, ooh, this my shit, this my shit\r\n" + "Ooh, ooh, this my shit, this my shit\r\n"
				+ "Ooh, ooh, this my shit, this my shit\r\n" + "So that's right dude, meet me at the bleachers\r\n"
				+ "No principals, no student-teachers\r\n"
				+ "Both of us want to be the winner, but there can only be one\r\n"
				+ "So I'm gonna fight, gonna give it my all\r\n" + "Gonna make you fall, gonna sock it to you\r\n"
				+ "That's right I'm the last one standing, another one bites the dust\r\n"
				+ "Few times I've been around that track\r\n" + "So it's not just gonna happen like that\r\n"
				+ "'Cause I ain't no hollaback girl\r\n" + "I ain't no hollaback girl\r\n"
				+ "A few times I've been around that track\r\n" + "So it's not just gonna happen like that\r\n"
				+ "'Cause I ain't no hollaback girl\r\n" + "I ain't no hollaback girl\r\n"
				+ "Ooh, ooh, this my shit, this my shit\r\n" + "Ooh, ooh, this my shit, this my shit\r\n"
				+ "Ooh, ooh, this my shit, this my shit\r\n" + "Ooh, ooh, this my shit, this my shit\r\n"
				+ "Let me hear you say, this shit is bananas\r\n" + "B-A-N-A-N-A-S\r\n" + "This shit is bananas\r\n"
				+ "B-A-N-A-N-A-S\r\n" + "Again, the shit is bananas\r\n" + "B-A-N-A-N-A-S\r\n"
				+ "This shit is bananas\r\n" + "B-A-N-A-N-A-S\r\n" + "A few times I've been around that track\r\n"
				+ "So it's not just gonna happen like that\r\n" + "'Cause I ain't no hollaback girl\r\n"
				+ "I ain't no hollaback girl\r\n" + "A few times I've been around that track\r\n"
				+ "So it's not just gonna happen like that\r\n" + "'Cause I ain't no hollaback girl\r\n"
				+ "I ain't no hollaback girl\r\n" + "Ooh, ooh, this my shit, this my shit\r\n"
				+ "Ooh, ooh, this my shit, this my shit\r\n" + "Ooh, ooh, this my shit, this my shit\r\n"
				+ "Ooh, ooh, this my shit, this my shit"));

		SearchEngine m = new SearchEngine();

		PopMusic[] music = new PopMusic[list.size()];
		HashTable<PopMusic> hashList = new HashTable<PopMusic>(list.toArray(music), list.size() * 3);

		m.writeFile(hashList, SearchEngine.MUSIC_FILEPATH);
		HashTable<PopMusic> musicTable = (HashTable<PopMusic>) m.readFile(SearchEngine.MUSIC_FILEPATH);

		System.out.println(musicTable.toString());
	}

}
